### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dcrystalj** [Nomados/STM32F4Discovery-ethernet-PHY-DP83848-demo-ChibiOS#1]
i plugged ehternet to router, changed gateway to my router settings like this
# define GW_ADDR0   192
# define GW_ADDR1   168
# define GW_ADDR2   1
# define GW_ADDR3   1

static ip to 
/_Static IP ADDRESS_/
# define IP_ADDR0   192
# define IP_ADDR1   168
# define IP_ADDR2   1
# define IP_ADDR3   111

commented out lcd  and make use for DHCP and RMII mode
//#define USE_LCD        /\* enable LCD  */  
# define USE_DHCP
# define RMII_MODE

i compile project with make command using yagarto tools. when i download program leds are blinking, but router doesnt get it

Any ideas?

**Comment by Nomados** [comment]
What PHY you use? Check in board.h file. Also be shure of using short wires.
10.02.2014 2:38 пользователь "Tomaz" notifications@github.com написал:

**Comment by dcrystalj** [comment]
I have Open407V-D board (http://www.wvshare.com/product/Open407V-D-Standard.htm with Ethernet) and on it STM32 F4 discovery

**Comment by Nomados** [comment]
I have the same board and this demo should run on it without any modifications. Check network settings and use direct network cable (without router)

**Comment by dcrystalj** [comment]
woow thank you very very much! i have tried direct connection and it's working. I was wrong going to ip 192.168.0.10. instead of 192.168.0.136. I have no idea where this 136 is defined.

Do you have same project but instead of chibiOS with FreeRTOS?

**Comment by Nomados** [comment]
I used this FreeRTOS demo as a base for this project. 
http://blog.tkjelectronics.dk/2012/08/ethernet-on-stm32f4discovery-using-external-phy/
But IMHO Chibios is much more powerful than FreeRTOS, so I recommend you to use it )

**Comment by dcrystalj** [comment]
actually there is coocox project but without freeRTOS.
I need freeRTOS just because i have one porject done (in freeRTOS https://github.com/dcrystalj/heating-automation) which I want to expand on internet.

Can you please tell me where is 192.168.0.136 in your project? I did grep on project but couldn found it.

**Comment by Nomados** [comment]
Haha, it's a little bit late, but anyway... You can change IP address here:
STM32F4Discovery-ethernet-PHY-DP83848-demo-ChibiOS/ch/os/various/lwip_bindings/lwipthread.h
